% clear all;
root_dir = [ 'Result/'];
root_dir = [root_dir 'mnist_mul/'];
test_Mnist(root_dir);
clear all;
root_dir = [root_dir 'protein_mul/'];
test_Protein(root_dir);
clear all;
root_dir = [root_dir 'svhn_mul/'];
test_SVHN(root_dir);
clear all;
root_dir = [root_dir 'usps_mul/'];
test_Usps(root_dir);
clear all;
root_dir = [root_dir 'imagenet_mul/'];
test_Imagenet(root_dir);
maxNumCompThreads(1);
clear all;
root_dir = [ 'Result/'];
root_dir = [root_dir 'mnist_sin/'];
test_Mnist(root_dir);
clear all;
root_dir = [root_dir 'protein_sin/'];
test_Protein(root_dir);
clear all;
root_dir = [root_dir 'svhn_sin/'];
test_SVHN(root_dir);
clear all;
root_dir = [root_dir 'usps_sin/'];
test_Usps(root_dir);
clear all;
root_dir = [root_dir 'imagenet_sin/'];
test_Imagenet(root_dir);
